### ISSUE TITLE
Xtext does not build with tycho 5 anymore

### ISSUE THREAD

**Issue by cdietrich** [xtext/xtext-reference-projects#402]
Xtext does not build with tycho 5 anymore

https://ci.eclipse.org/xtext/job/xtext/job/cd_tycho50/

**Comment by LorenzoBettini** [comment]
```
[INFO] --- bundle:5.1.8:manifest (bundle-manifest) @ org.eclipse.xtext.web
...
[ERROR] Failed to execute goal org.apache.felix:maven-bundle-plugin:5.1.8:manifest (bundle-manifest) on project org.eclipse.xtext.web: Execution bundle-manifest of goal org.apache.felix:maven-bundle-plugin:5.1.8:manifest failed: An API incompatibility was encountered while executing org.apache.felix:maven-bundle-plugin:5.1.8:manifest: java.lang.NoSuchMethodError: 'void aQute.bnd.osgi.Jar.setReproducible(boolean)'
```

We use maven-bundle-plugin:5.1.8, but the latest one is 5.1.9.

Or maybe related:

https://github.com/bndtools/bnd/issues/3146

https://github.com/bndtools/bnd/issues/2242

**Comment by LorenzoBettini** [comment]
@cdietrich By the way, this issue should be in the Xtext repository, not here, right?

**Comment by cdietrich** [comment]
yes i used the wrong repo. have no time to work and xtext so was in a big hurry
